language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install mock
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script: coverage run --source=cdl_convert.py tests/test_cdl_convert.py
# command to run after tests have completed
after_success:
  coveralls